#!/usr/bin/perl

use strict;
use 5.022;

BEGIN {use FindBin qw($Bin); require "$Bin/_init.pl"};

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('Pouet2');
